add tests for NSSKeyManager
TODO: executing those tests with `cargo test --features keydb` fails
because nss will be initialized without profile dir first:
```
thread 'encryption::keydb_test::test_nss_key_manager' panicked at components/logins/src/encryption.rs:401:87:
called `Result::unwrap()` on an `Err` value: NSSInitializationFailed { reason: "NSS could not be initialized: NSS has been already initialized without profile" }
```