Revert "Update Rust version to 1.75, MSR to 1.70"
This reverts commit 3c43e3fb4a0940d3ee98fe26bf96a5825c160ee6 due to
obscure Mac errors like:
```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      __ZN3std3sys4unix4time8Timespec3now17h3d563c28f99d32cbE.llvm.6221371515776009879 in megazord.std-f4038c6a2122598b.std.69f244de2863e905-cgu.0.rcgu.o.rcgu.o
  "_getentropy", referenced from:
      __ZN3std3sys4unix4rand19hashmap_random_keys17h694f1d109e8c2473E in megazord.std-f4038c6a2122598b.std.69f244de2863e905-cgu.0.rcgu.o.rcgu.o
ld: symbol(s) not found for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```