Remove unused unlock_notify feature from rustqlite.
This was causing my build to fail locally with an undefined reference to
sqlite3_unlock_notify. It seems nothing makes use of this feature tho.